version: '3'

services:
  api:
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/reservations
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      DEBUG: "true"
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      REDIS_HOST: redis

  postgres:
    restart: always
    image: postgres:latest

  redis:
    restart: always
    image: redis:latest
