# Generated by Django 2.0.1 on 2018-01-16 01:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('in_date', models.DateField()),
                ('out_date', models.DateField()),
                ('checkin_datetime', models.DateTimeField(null=True)),
                ('checkout_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('in_date',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Room'),
        ),
    ]
