# Generated by Django 2.0.1 on 2018-01-16 01:34

from django.db import migrations
import enumchoicefield.fields
import reservations.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=reservations.api.models.ReservationState(1), enum_class=reservations.api.models.ReservationState, max_length=11),
        ),
    ]
