# Generated by Django 2.0.1 on 2018-01-19 00:46

from django.db import migrations, models
import enumchoicefield.fields
import reservations.api.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20180117_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAndUpcomingReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_id', models.UUIDField(editable=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('in_date', models.DateField(editable=False)),
                ('out_date', models.DateField(editable=False)),
                ('room_number', models.CharField(max_length=255)),
                ('checkin_datetime', models.DateTimeField(null=True)),
                ('checkout_datetime', models.DateTimeField(null=True)),
                ('status', enumchoicefield.fields.EnumChoiceField(default=reservations.api.models.ReservationState(1), enum_class=reservations.api.models.ReservationState, max_length=11)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
