# Generated by Django 2.0.1 on 2018-01-19 06:12

from django.db import migrations, models
import enumchoicefield.fields
import reservations.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_currentandupcomingreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='in_date',
            field=models.DateField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='out_date',
            field=models.DateField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(db_index=True, default=reservations.api.models.ReservationState(1), enum_class=reservations.api.models.ReservationState, max_length=11),
        ),
    ]
