# Generated by Django 2.0.1 on 2018-01-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20180117_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='in_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='out_date',
            field=models.DateField(editable=False),
        ),
    ]
